# Generated by Django 5.0.6 on 2024-07-23 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0009_category_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views_tr',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
