# Generated by Django 5.0.6 on 2024-07-31 13:54

import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tcore', '0011_setting_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcore.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Oluşuturulma Zamanı'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Güncellenme Zamanı'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Görüntüleme'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=30, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='Address',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='district',
            field=models.CharField(max_length=100, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(max_length=255, verbose_name='Facebook Adresi'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='fax',
            field=models.CharField(max_length=10, verbose_name='Faks'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram_url',
            field=models.URLField(max_length=255, verbose_name='Instagram Adresi'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='Anaktar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Anaktar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Anaktar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo1',
            field=models.ImageField(blank=True, null=True, upload_to='dimg', verbose_name='Logo 1'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='dimg', verbose_name='Logo 2'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phohe_fixed',
            field=models.CharField(max_length=10, verbose_name='Sabit Telefon'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phohe_mobil',
            field=models.CharField(max_length=10, verbose_name='Cep Telefonu'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='postal_code',
            field=models.CharField(max_length=7, verbose_name='Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='x_url',
            field=models.URLField(max_length=255, verbose_name='X Adresi'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube_url',
            field=models.URLField(max_length=255, verbose_name='Youtube Adresi'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlık'),
        ),
    ]
