from django.utils.translation import gettext_lazy as _
"""
Django settings for corporate project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('IS_DEV')

ALLOWED_HOSTS = [os.getenv('APP_HOST')]


# Application definition

INSTALLED_APPS = [
    'tcore',
    'ckeditor',
    'taggit',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'corporate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'tcore.context_processors.SettingList',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'corporate.wsgi.application'








DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'corporate',
        'USER': 'root',
        'PASSWORD': '****',
        'HOST': 'localhost', 
        'PORT': '3306',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'tr'


LANGUAGES=[
    ('tr',_('Turkish')),
    ('en',_('English')),
    
]

MODEL_TRANSLATİON_DEFAULT_LANGUAGE='tr'
MODELTRANSLATİON_LANGUAGE=('tr','en')


#ana dilimizin tr olduğunu belirtiyoruz


TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True #Uluslararasılaştırma?
USE_I10N= True  #Yerelleştirme?
USE_TZ = True   #Zaman dilimi?


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (BASE_DIR,'static')
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_URL = 'media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]





# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#SMTP Settings(Mail gönderim protokolü)

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST=os.getenv('EMAIL_HOST')               #mail sunucusu
EMAIL_PORT=587                                   #port
EMAIL_USE_TLS=True                               #SSL güvenlik sertifikası var mı 
EMAIL_HOST_USER=os.getenv('EMAIL_HOST_USER')         #hangi mail adresinden gidicek
EMAIL_HOST_PASSWORD=os.getenv('EMAIL_HOST_PASSWORD')             #mail göndermek için bir üstteki mailin şifresi