# Generated by Django 5.0.6 on 2024-07-23 13:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0008_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_tr', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_tr', models.CharField(max_length=30, null=True)),
                ('title_en', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(upload_to='', verbose_name='blog')),
                ('image_tr', models.ImageField(null=True, upload_to='', verbose_name='blog')),
                ('image_en', models.ImageField(null=True, upload_to='', verbose_name='blog')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_at_tr', models.DateField(auto_now_add=True, null=True)),
                ('created_at_en', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('updated_at_tr', models.DateField(auto_now=True, null=True)),
                ('updated_at_en', models.DateField(auto_now=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('views_tr', models.IntegerField(default=0, null=True)),
                ('views_en', models.IntegerField(default=0, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=30, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcore.category')),
            ],
        ),
    ]
