# Generated by Django 5.0.7 on 2024-08-02 14:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0012_blog_tags_alter_about_content_alter_about_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='içerik')),
                ('content_tr', ckeditor.fields.RichTextField(null=True, verbose_name='içerik')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='içerik')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
            ],
        ),
    ]
