# Generated by Django 5.0.7 on 2024-08-05 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0014_alter_page_content_alter_page_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('content_tr', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
        ),
       
    ]
